printWidth: 100
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
trailingComma: all
bracketSpacing: true
arrowParens: always
overrides:
  - files: '*.{yaml,yml,json,md,tf}'
    options:
      tabWidth: 2
